version: "3"

volumes:
  pgdata:

services:
  pagila:
    image: postgres:13.2
    container_name: pagila
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    volumes:
      - .:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432